webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
   - ./doc_root:/app
   - ./conf:/bitnami/nginx/conf

nginx:
  image: bitnami/nginx
  ports:
    - "8083:80"
  volumes:
   - ./doc_root:/app
   - ./conf:/bitnami/nginx/conf
