webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
   - ./doc_root:/app
   - ./conf:/bitnami/nginx/conf

nginx:
  image: bitnami/nginx
  ports:
    - "8082:80"
  volumes_from:
    - webdata
  restart: always
